version: '3.8'

services:
  pgsql:
    container_name: pgsql-container
    image: postgres:alpine
    ports:
      - 15432:5432
    networks:
      - pgsql-network
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
  backend:
    container_name: backend-container
    env_file: ./.env
    build: .
    ports:
      - 3000:3000
    networks:
      - pgsql-network
    depends_on:
      - pgsql
    environment:
      DATABASE_URL: postgres://test:test@pgsql-container:5432/test
      HOST_URL: http://localhost:3000
      PORT: 3000
volumes:
  pgsql-volume:
    driver: local
networks:
  pgsql-network:
    external: true