version: '3.8'

services:
  pgsql:
    container_name: pgsql-container
    image: postgres:alpine
    ports:
      - 15432:5432
    networks:
      - pgsql-network
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgsql-volume:/var/lib/postgresql/data

  backend:
    container_name: backend-container
    build:
      context: .
      target: backend
    networks:
      - pgsql-network
    depends_on:
      - pgsql
    env_file: ./.env
    environment:
      DATABASE_URL: postgres://test:test@pgsql-container:5432/test
      HOST_URL: http://localhost:8000
      PORT: 8000
      HOST: 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: air -c .air.conf

  frontend:
    container_name: frontend-container
    build:
      context: .
      target: frontend
    networks:
      - pgsql-network
    environment:
      HOST: 0.0.0.0
      HOST_URL: http://backend-container:8000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install; yarn dev"

volumes:
  pgsql-volume:
    external: true

networks:
  pgsql-network:
    external: true
