version: '3.8'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
  backend:
    env_file: ./.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://test:test@localhost:15432/test
      PORT: 3000